### n-gram and bag of words

Set of all sequential words of n words or less. For example for the sentence "hi im noah", the bag of 2 gram would be:

{hi,im,noah,hi im, im noah}

In [10]:
#One hot encoding
import numpy as np
samples = ['the cat sat on the mat', 'the dog ate my homework']
oneHotEncoding = {}
for sample in samples:
    split = sample.split()
    for i in range(len(split)):
        if split[i] not in oneHotEncoding:
            oneHotEncoding[split[i]] = len(oneHotEncoding)
print("Encodings",oneHotEncoding)
maxWords = 10
results = np.zeros((len(samples),maxWords, len(oneHotEncoding)))

for i,sample in enumerate(samples):
    for x,word in enumerate(sample.split()):
        results[i,x,oneHotEncoding[word]] = 1
print("One hot encoding: \n",results)

Encodings {'the': 0, 'cat': 1, 'sat': 2, 'on': 3, 'mat': 4, 'dog': 5, 'ate': 6, 'my': 7, 'homework': 8}
One hot encoding: 
 [[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [17]:
#Built in one hot encoding:

from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words = 1000)
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)
oneHot = tokenizer.sequences_to_matrix(sequences, mode='binary')


In [21]:
oneHot.shape

(2, 1000)

## Word embeddings pack more information into less dimensions


Learning word embeddings:

Map words together geometrically that have similar meanins

Perfect embedding space differs depending on problem looking at


In [25]:
from keras.layers import Embedding
embeddedLayer = Embedding(1000,64)
#This layer is a dictionary to vector that represents word

In [34]:
from keras.datasets import imdb
from keras import preprocessing

maxFeatures = 10000    #10000 most common words
maxLen = 20            #Cut off each review after 20 first words

(xTrain,yTrain), (xTest,yTest) = imdb.load_data(num_words = maxFeatures)
print(xTrain[0])

xTrain = preprocessing.sequence.pad_sequences(xTrain, maxlen = maxLen)
xTest = preprocessing.sequence.pad_sequences(xTest, maxlen = maxLen)


[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [33]:
xTrain

array([[  65,   16,   38, ...,   19,  178,   32],
       [  23,    4, 1690, ...,   16,  145,   95],
       [1352,   13,  191, ...,    7,  129,  113],
       ...,
       [  11, 1818, 7561, ...,    4, 3586,    2],
       [  92,  401,  728, ...,   12,    9,   23],
       [ 764,   40,    4, ...,  204,  131,    9]], dtype=int32)

In [42]:
from keras.models import Sequential
from keras.layers import Dense, Flatten

model = Sequential()
model.add(Embedding(10000,8, input_length = maxLen))
model.add(Flatten())
model.add(Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.fit(xTrain,yTrain, epochs=10, validation_split = 0.2, batch_size = 32)

Epoch 1/10
625/625 [==============================] - 1s 1ms/step - loss: 0.6582 - accuracy: 0.6409 - val_loss: 0.5997 - val_accuracy: 0.7044
Epoch 2/10
625/625 [==============================] - 1s 934us/step - loss: 0.5235 - accuracy: 0.7583 - val_loss: 0.5204 - val_accuracy: 0.7304
Epoch 3/10
625/625 [==============================] - 1s 874us/step - loss: 0.4530 - accuracy: 0.7914 - val_loss: 0.4987 - val_accuracy: 0.7476
Epoch 4/10
625/625 [==============================] - 1s 882us/step - loss: 0.4175 - accuracy: 0.8102 - val_loss: 0.4957 - val_accuracy: 0.7578
Epoch 5/10
625/625 [==============================] - 1s 833us/step - loss: 0.3923 - accuracy: 0.8227 - val_loss: 0.4949 - val_accuracy: 0.7590
Epoch 6/10
625/625 [==============================] - 1s 827us/step - loss: 0.3720 - accuracy: 0.8351 - val_loss: 0.4993 - val_accuracy: 0.7596
Epoch 7/10
625/625 [==============================] - 1s 1ms/step - loss: 0.3542 - accuracy: 0.8464 - val_loss: 0.5064 - val_accuracy: 0.7