In [2]:
import pandas as pd
directory = '/home/noah/Datasets/books.csv'
df = pd.read_csv(directory)
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [17]:
print("Number of fiction books: ", df.loc[df['Genre']=='Fiction','Genre'].size)
print("Number of non fiction books: ", df.loc[df['Genre']=='Non Fiction','Genre'].size)

Number of fiction books:  240
Number of non fiction books:  310


In [20]:
authors = df['Author'].unique()

248

In [29]:
for group in df.groupby('Author'):
    print(group)

('Abraham Verghese',                  Name            Author  User Rating  Reviews  Price  Year  \
56  Cutting for Stone  Abraham Verghese          4.6     4866     11  2010   
57  Cutting for Stone  Abraham Verghese          4.6     4866     11  2011   

      Genre  
56  Fiction  
57  Fiction  )
('Adam Gasiewski',                                                   Name          Author  \
232  Milk and Vine: Inspirational Quotes From Class...  Adam Gasiewski   

     User Rating  Reviews  Price  Year        Genre  
232          4.4     3113      6  2017  Non Fiction  )
('Adam Mansbach',                      Name         Author  User Rating  Reviews  Price  Year  \
133  Go the F**k to Sleep  Adam Mansbach          4.8     9568      9  2011   

       Genre  
133  Fiction  )
('Adir Levy',                                                   Name     Author  \
529  What Should Danny Do? (The Power to Choose Ser...  Adir Levy   

     User Rating  Reviews  Price  Year    Genre  
529          

('Donna Tartt',                                                   Name       Author  \
392  The Goldfinch: A Novel (Pulitzer Prize for Fic...  Donna Tartt   
393  The Goldfinch: A Novel (Pulitzer Prize for Fic...  Donna Tartt   

     User Rating  Reviews  Price  Year    Genre  
392          3.9    33844     20  2013  Fiction  
393          3.9    33844     20  2014  Fiction  )
('Doug Lemov',                                                   Name      Author  \
316  Teach Like a Champion: 49 Techniques that Put ...  Doug Lemov   
317  Teach Like a Champion: 49 Techniques that Put ...  Doug Lemov   

     User Rating  Reviews  Price  Year        Genre  
316          4.4      637     20  2010  Non Fiction  
317          4.4      637     20  2011  Non Fiction  )
('Dr. Seuss',                                        Name     Author  User Rating  Reviews  \
245               Oh, the Places You'll Go!  Dr. Seuss          4.9    21834   
246               Oh, the Places You'll Go!  Dr. Seuss  

('Marie Kondō',                                                   Name       Author  \
423  The Life-Changing Magic of Tidying Up: The Jap...  Marie Kondō   
424  The Life-Changing Magic of Tidying Up: The Jap...  Marie Kondō   
425  The Life-Changing Magic of Tidying Up: The Jap...  Marie Kondō   
426  The Life-Changing Magic of Tidying Up: The Jap...  Marie Kondō   

     User Rating  Reviews  Price  Year        Genre  
423          4.5    22641     11  2015  Non Fiction  
424          4.5    22641     11  2016  Non Fiction  
425          4.5    22641     11  2017  Non Fiction  
426          4.5    22641     11  2019  Non Fiction  )
('Marjorie Sarnat',                                                  Name           Author  \
54  Creative Haven Creative Cats Coloring Book (Ad...  Marjorie Sarnat   
55  Creative Haven Owls Coloring Book (Adult Color...  Marjorie Sarnat   

    User Rating  Reviews  Price  Year        Genre  
54          4.8     4022      4  2015  Non Fiction  
55      

411    16949     30  2012  Fiction  )
('Ta-Nehisi Coates',                         Name            Author  User Rating  Reviews  Price  \
35  Between the World and Me  Ta-Nehisi Coates          4.7    10070     13   
36  Between the World and Me  Ta-Nehisi Coates          4.7    10070     13   

    Year        Genre  
35  2015  Non Fiction  
36  2016  Non Fiction  )
('Tara Westover',                   Name         Author  User Rating  Reviews  Price  Year  \
97  Educated: A Memoir  Tara Westover          4.7    28729     15  2018   
98  Educated: A Memoir  Tara Westover          4.7    28729     15  2019   

          Genre  
97  Non Fiction  
98  Non Fiction  )
('Tatiana de Rosnay',             Name             Author  User Rating  Reviews  Price  Year  \
292  Sarah's Key  Tatiana de Rosnay          4.6     3619     10  2010   

       Genre  
292  Fiction  )
('The College Board',                                                   Name             Author  \
439                       T

In [35]:
seqLengths = [len(sequence.split()) for sequence in df['Name'].to_numpy()]
maxLength = max(seqLengths)
print("Max words in a title is: ", maxLength)

Max words in a title is:  24


In [152]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
maxWords = 1000
maxLen = maxLength

tok = Tokenizer(num_words = maxWords)
tok.fit_on_texts(df['Name'])
sequences = tok.texts_to_sequences(df['Name'])
matrix = tok.texts_to_matrix(df['Name'], mode = 'binary')
x = pad_sequences(sequences, maxlen = maxLen)
print(len(matrix[0]))
print("Matrix will be used for vanilla neural network: \n", matrix)
print("x will be used for embedding/LSTM \n", x)

1000
Matrix will be used for vanilla neural network: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
x will be used for embedding/LSTM 
 [[  0   0   0 ... 609 610 611]
 [  0   0   0 ... 612   3  15]
 [  0   0   0 ... 614   5 615]
 ...
 [  0   0   0 ...  21 169  13]
 [  0   0   0 ...  21 169  13]
 [  0   0   0 ...  21 169  13]]


In [58]:
import numpy as np
genre = df['Genre'].to_numpy()
yDict = {"Fiction": 0, "Non Fiction": 1}
y = np.zeros((len(genre)))
for i in range(len(genre)):
    y[i] = yDict[genre[i]]
print(y)

[1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0.
 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0.
 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0.
 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0.
 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1.
 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 1.
 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0.
 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [66]:
print(x.shape[0]== y.shape[0])

True


In [103]:
#First try vanilla neural network
from keras.layers import Dense, Dropout
from keras.models import Sequential

model = Sequential()
model.add(Dense(64, activation = 'relu',input_shape = (1000,)))


model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.fit(matrix,y, epochs = 20, validation_split = .2)

Epoch 1/20
14/14 [==============================] - 0s 8ms/step - loss: 0.6448 - accuracy: 0.6841 - val_loss: 0.6385 - val_accuracy: 0.6000
Epoch 2/20
14/14 [==============================] - 0s 2ms/step - loss: 0.5542 - accuracy: 0.8091 - val_loss: 0.6014 - val_accuracy: 0.6727
Epoch 3/20
14/14 [==============================] - 0s 2ms/step - loss: 0.4751 - accuracy: 0.9091 - val_loss: 0.5623 - val_accuracy: 0.7364
Epoch 4/20
14/14 [==============================] - 0s 2ms/step - loss: 0.4017 - accuracy: 0.9568 - val_loss: 0.5240 - val_accuracy: 0.7727
Epoch 5/20
14/14 [==============================] - 0s 2ms/step - loss: 0.3364 - accuracy: 0.9682 - val_loss: 0.4885 - val_accuracy: 0.8273
Epoch 6/20
14/14 [==============================] - 0s 2ms/step - loss: 0.2798 - accuracy: 0.9659 - val_loss: 0.4569 - val_accuracy: 0.8273
Epoch 7/20
14/14 [==============================] - 0s 3ms/step - loss: 0.2331 - accuracy: 0.9773 - val_loss: 0.4321 - val_accuracy: 0.8273
Epoch 8/20
14/14 [==

In [126]:
def textToMatrix(text):
    mat = tok.texts_to_matrix([text], mode = 'binary')
    return mat


def predictWithVanilla(text):
    mat = textToMatrix(text)
    pred = model.predict(mat)
    if(pred[0][0]<0.5):
        print("For the book title of: \"" + text+ "\" =====> predicted fiction")
    else:
        print("For the book title of: \"" + text+ "\" =====> predicted non fiction")
    
predictWithVanilla("lord of the rings")
predictWithVanilla("learn probability theory")
predictWithVanilla("the hobbit")
predictWithVanilla("history of the united states")
predictWithVanilla("working from home")
predictWithVanilla("diet 101")

For the book title of: "lord of the rings" =====> predicted fiction
For the book title of: "learn probability theory" =====> predicted non fiction
For the book title of: "the hobbit" =====> predicted fiction
For the book title of: "history of the united states" =====> predicted non fiction
For the book title of: "working from home" =====> predicted non fiction
For the book title of: "diet 101" =====> predicted non fiction


In [127]:
predictWithVanilla("harry potter")

For the book title of: "harry potter" =====> predicted fiction


In [128]:
predictWithVanilla("mouse and motorcycle")

For the book title of: "mouse and motorcycle" =====> predicted non fiction


In [162]:
#Next will use word embeddings
from keras.layers import Embedding, Flatten
model2 = Sequential()
model2.add(Embedding(maxWords,8, input_length = maxLen))
model2.add(Flatten())
model2.add(Dense(32, activation = 'relu'))
model2.add(Dense(1, activation = 'sigmoid'))
model2.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])
model2.fit(x,y, epochs = 50, validation_split = .2)



Epoch 1/50
14/14 [==============================] - 0s 8ms/step - loss: 0.6937 - accuracy: 0.5159 - val_loss: 0.6924 - val_accuracy: 0.5273
Epoch 2/50
14/14 [==============================] - 0s 2ms/step - loss: 0.6877 - accuracy: 0.5932 - val_loss: 0.6922 - val_accuracy: 0.5273
Epoch 3/50
14/14 [==============================] - 0s 2ms/step - loss: 0.6819 - accuracy: 0.6341 - val_loss: 0.6929 - val_accuracy: 0.5182
Epoch 4/50
14/14 [==============================] - 0s 2ms/step - loss: 0.6738 - accuracy: 0.6841 - val_loss: 0.6942 - val_accuracy: 0.4909
Epoch 5/50
14/14 [==============================] - 0s 2ms/step - loss: 0.6624 - accuracy: 0.7091 - val_loss: 0.6955 - val_accuracy: 0.4909
Epoch 6/50
14/14 [==============================] - 0s 2ms/step - loss: 0.6469 - accuracy: 0.7386 - val_loss: 0.6964 - val_accuracy: 0.4909
Epoch 7/50
14/14 [==============================] - 0s 2ms/step - loss: 0.6281 - accuracy: 0.7500 - val_loss: 0.7003 - val_accuracy: 0.5091
Epoch 8/50
14/14 [==

Guess embeddings are not working to well...maybe need more data?

In [166]:
#LSTM
from keras.layers import LSTM
model3 = Sequential()
model3.add(Embedding(maxWords, 32))
model3.add(LSTM(32))
model3.add(Dense(1,activation = 'sigmoid'))
model3.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])
model3.fit(x,y, epochs = 20, validation_split = .2)

Epoch 1/20
14/14 [==============================] - 0s 34ms/step - loss: 0.6937 - accuracy: 0.4705 - val_loss: 0.6928 - val_accuracy: 0.5364
Epoch 2/20
14/14 [==============================] - 0s 10ms/step - loss: 0.6891 - accuracy: 0.6227 - val_loss: 0.6923 - val_accuracy: 0.5273
Epoch 3/20
14/14 [==============================] - 0s 8ms/step - loss: 0.6801 - accuracy: 0.6727 - val_loss: 0.6920 - val_accuracy: 0.5364
Epoch 4/20
14/14 [==============================] - 0s 8ms/step - loss: 0.6584 - accuracy: 0.6614 - val_loss: 0.6976 - val_accuracy: 0.4909
Epoch 5/20
14/14 [==============================] - 0s 8ms/step - loss: 0.6239 - accuracy: 0.7023 - val_loss: 0.7253 - val_accuracy: 0.5182
Epoch 6/20
14/14 [==============================] - 0s 9ms/step - loss: 0.5885 - accuracy: 0.7159 - val_loss: 0.7304 - val_accuracy: 0.5273
Epoch 7/20
14/14 [==============================] - 0s 9ms/step - loss: 0.5481 - accuracy: 0.7364 - val_loss: 0.7917 - val_accuracy: 0.5182
Epoch 8/20
14/14 [

Same deal as just using embedding. LSTMs/Embeddings probably require a lot more data as the need to learn more complex relationships.