In [2]:
import numpy as np
import csv
with open('/home/noah/Datasets/AAPLStock.csv', 'r') as f:
    aapl = list(csv.reader(f, delimiter=';'))
data = np.asarray(aapl[1:])
headers = np.asarray(aapl[0][0].split(",")[1:10])
headers

array(['open', 'high', 'low', 'close', 'volume', 'unadjustedVolume',
       'change', 'changePercent', 'vwap'], dtype='<U16')

In [43]:
#Clean data
cleanData = np.zeros((len(data), 3))

for i,sample in enumerate(data):
    for j,feature in enumerate(sample):
    
        cleanedSample = data[i][0].replace("\''","").replace("\"", "").split(',')[1:4]
        cleanData[i] = cleanedSample
cleanData.shape
import numpy as np
from sklearn.preprocessing import normalize
cleanData = normalize(cleanData, axis = 0)

In [46]:
lookback = 5
size = len(cleanData)
nFeatures = cleanData.shape[-1]
x = np.zeros((size-lookback,lookback, nFeatures))
y = np.zeros((size-lookback, nFeatures))

for i in range(size-lookback-1):
    y[i] = cleanData[i+lookback+1]
    x[i] = cleanData[i:i+lookback]
x

array([[[0.01470507, 0.01462658, 0.01460803],
        [0.01443893, 0.01449935, 0.01454733],
        [0.01461088, 0.01448964, 0.01450779],
        [0.01445162, 0.01436472, 0.01435742],
        [0.01427305, 0.01446816, 0.01436995]],

       [[0.01443893, 0.01449935, 0.01454733],
        [0.01461088, 0.01448964, 0.01450779],
        [0.01445162, 0.01436472, 0.01435742],
        [0.01427305, 0.01446816, 0.01436995],
        [0.0146026 , 0.01457679, 0.01453898]],

       [[0.01461088, 0.01448964, 0.01450779],
        [0.01445162, 0.01436472, 0.01435742],
        [0.01427305, 0.01446816, 0.01436995],
        [0.0146026 , 0.01457679, 0.01453898],
        [0.01444637, 0.01451933, 0.01455819]],

       ...,

       [[0.03551399, 0.03555491, 0.03570977],
        [0.0359469 , 0.0356695 , 0.03588575],
        [0.03574726, 0.03562575, 0.03598116],
        [0.03601836, 0.03593409, 0.03602781],
        [0.0356653 , 0.03568023, 0.03591331]],

       [[0.0359469 , 0.0356695 , 0.03588575],
        [0.03

In [59]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
model = Sequential()
model.add(LSTM(32))
model.add(Dense(3, activation = 'relu'))\

model.compile( optimizer = 'rmsprop', loss = 'mae', metrics = ['accuracy'])
model.fit(x,y,epochs = 100, batch_size = 32)


Epoch 1/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0128 - accuracy: 0.2626
Epoch 2/100
40/40 [==============================] - 0s 3ms/step - loss: 0.0111 - accuracy: 0.2570
Epoch 3/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0108 - accuracy: 0.2586
Epoch 4/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0108 - accuracy: 0.2298
Epoch 5/100
40/40 [==============================] - 0s 3ms/step - loss: 0.0107 - accuracy: 0.2466
Epoch 6/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0106 - accuracy: 0.2658
Epoch 7/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0105 - accuracy: 0.2330
Epoch 8/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0105 - accuracy: 0.2658
Epoch 9/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0104 - accuracy: 0.2259
Epoch 10/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0104 - accuracy: 0.2458
Epoch 11/

40/40 [==============================] - 0s 2ms/step - loss: 0.0100 - accuracy: 0.2658
Epoch 84/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 0.2442
Epoch 85/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 0.2370
Epoch 86/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 0.2275
Epoch 87/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 0.2562
Epoch 88/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 0.2713
Epoch 89/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 0.2650
Epoch 90/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 0.2538
Epoch 91/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 0.2338
Epoch 92/100
40/40 [==============================] - 0s 3ms/step - loss: 0.0099 - accuracy: 0.2402
Epoch 93/100


x

In [60]:


model.predict(x[0:2])

array([[0.01339916, 0.01371498, 0.        ],
       [0.01347154, 0.013785  , 0.        ]], dtype=float32)

In [61]:
x[1]

array([[0.01443893, 0.01449935, 0.01454733],
       [0.01461088, 0.01448964, 0.01450779],
       [0.01445162, 0.01436472, 0.01435742],
       [0.01427305, 0.01446816, 0.01436995],
       [0.0146026 , 0.01457679, 0.01453898]])

In [62]:
y[1]

array([0.01465558, 0.01457376, 0.0146963 ])